/**
 * `localpress completions` — generate shell completion scripts.
 *
 * Outputs completion scripts for bash, zsh, or fish to stdout.
 * Users pipe the output to the appropriate shell config file.
 *
 * Usage:
 *   localpress completions bash >> ~/.bashrc
 *   localpress completions zsh >> ~/.zshrc
 *   localpress completions fish > ~/.config/fish/completions/localpress.fish
 */

import type { Command } from 'commander';
import { error } from '../utils/output.ts';

const SHELLS = ['bash', 'zsh', 'fish'] as const;
type Shell = (typeof SHELLS)[number];

export function registerCompletionsCommand(program: Command): void {
  program
    .command('completions')
    .description('Generate shell completion scripts (bash, zsh, fish)')
    .argument('<shell>', `shell to generate completions for (${SHELLS.join(', ')})`)
    .action((shell: string) => {
      const normalized = shell.toLowerCase() as Shell;

      if (!SHELLS.includes(normalized)) {
        error(`Unknown shell: "${shell}". Supported: ${SHELLS.join(', ')}`);
        process.exit(2);
      }

      const script = generateCompletions(normalized);
      // Write directly to stdout (bypass info() which respects --quiet/--json).
      process.stdout.write(script);
    });
}

function generateCompletions(shell: Shell): string {
  switch (shell) {
    case 'bash':
      return generateBash();
    case 'zsh':
      return generateZsh();
    case 'fish':
      return generateFish();
  }
}

// -- Commands and options data ------------------------------------------------

const COMMANDS = [
  'init',
  'sites',
  'doctor',
  'config',
  'list',
  'show',
  'stats',
  'caption',
  'audit',
  'optimize',
  'convert',
  'resize',
  'remove-bg',
  'edit',
  'pull',
  'push',
  'references',
  'update',
  'completions',
  'help',
];

const GLOBAL_OPTIONS = [
  '--site',
  '--json',
  '--quiet',
  '--concurrency',
  '--dry-run',
  '--apply',
  '--yes',
  '--strict',
  '--help',
  '--version',
];

// -- Bash completions ---------------------------------------------------------

function generateBash(): string {
  return `# localpress bash completion
# Generated by: localpress completions bash
# Add to ~/.bashrc or ~/.bash_profile:
#   eval "$(localpress completions bash)"
# Or:
#   localpress completions bash >> ~/.bashrc

_localpress() {
  local cur prev commands global_opts
  COMPREPLY=()
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"

  commands="${COMMANDS.join(' ')}"
  global_opts="${GLOBAL_OPTIONS.join(' ')}"

  # Complete commands at position 1
  if [[ \${COMP_CWORD} -eq 1 ]]; then
    COMPREPLY=( $(compgen -W "\${commands} \${global_opts}" -- "\${cur}") )
    return 0
  fi

  # Complete global options and subcommand-specific options
  local cmd="\${COMP_WORDS[1]}"
  case "\${cmd}" in
    init)
      COMPREPLY=( $(compgen -W "--site --help" -- "\${cur}") )
      ;;
    sites)
      COMPREPLY=( $(compgen -W "list add remove use --help" -- "\${cur}") )
      ;;
    doctor)
      COMPREPLY=( $(compgen -W "--all-sites --plugins --fix --help" -- "\${cur}") )
      ;;
    config)
      COMPREPLY=( $(compgen -W "get set list set-profile get-profile list-profiles remove-profile --help" -- "\${cur}") )
      ;;
    list)
      COMPREPLY=( $(compgen -W "-i --interactive --unoptimized --type --sort --order --limit --page --help" -- "\${cur}") )
      ;;
    show)
      COMPREPLY=( $(compgen -W "--help" -- "\${cur}") )
      ;;
    stats)
      COMPREPLY=( $(compgen -W "--all-sites --help" -- "\${cur}") )
      ;;
    caption)
      COMPREPLY=( $(compgen -W "--missing-alt --model --prompt --list-models --help" -- "\${cur}") )
      ;;
    audit)
      COMPREPLY=( $(compgen -W "--unoptimized --large --missing-alt --display-size --duplicates --broken-refs --orphans --all --threshold --help" -- "\${cur}") )
      ;;
    optimize)
      COMPREPLY=( $(compgen -W "--all --unoptimized --quality --format --max-width --max-height --encoder --strip-metadata --profile --keep-original --preview --help" -- "\${cur}") )
      ;;
    convert)
      COMPREPLY=( $(compgen -W "--format --quality --encoder --keep-original --help" -- "\${cur}") )
      ;;
    resize)
      COMPREPLY=( $(compgen -W "--max-width --max-height --keep-original --help" -- "\${cur}") )
      ;;
    remove-bg)
      COMPREPLY=( $(compgen -W "--all --unoptimized --model --bg --trim --list-models --keep-original --rembg --rembg-model --preview --help" -- "\${cur}") )
      ;;
    edit)
      COMPREPLY=( $(compgen -W "--with --no-watch --keep-file --to --help" -- "\${cur}") )
      ;;
    pull)
      COMPREPLY=( $(compgen -W "--to --help" -- "\${cur}") )
      ;;
    push)
      COMPREPLY=( $(compgen -W "--title --alt --caption --description --post-id --help" -- "\${cur}") )
      ;;
    references)
      COMPREPLY=( $(compgen -W "--scope --update-to --help" -- "\${cur}") )
      ;;
    update)
      COMPREPLY=( $(compgen -W "--check --help" -- "\${cur}") )
      ;;
    completions)
      COMPREPLY=( $(compgen -W "bash zsh fish" -- "\${cur}") )
      ;;
    *)
      COMPREPLY=( $(compgen -W "\${global_opts}" -- "\${cur}") )
      ;;
  esac

  return 0
}

complete -F _localpress localpress
`;
}

// -- Zsh completions ----------------------------------------------------------

function generateZsh(): string {
  return `#compdef localpress
# localpress zsh completion
# Generated by: localpress completions zsh
# Add to ~/.zshrc:
#   eval "$(localpress completions zsh)"
# Or place in your fpath:
#   localpress completions zsh > ~/.zsh/completions/_localpress

_localpress() {
  local -a commands global_opts

  commands=(
    'init:Connect a WordPress site (interactive wizard)'
    'sites:Manage configured WordPress sites'
    'doctor:Show backend availability and capability matrix'
    'config:Read and write localpress configuration'
    'list:List media in the active site library'
    'show:Show metadata and history for an attachment'
    'stats:Show cumulative processing stats and library health'
    'caption:Generate alt-text using a local vision model'
    'audit:Find optimization opportunities across the media library'
    'optimize:Compress and optionally convert media'
    'convert:Convert attachments to a different format'
    'resize:Resize attachments preserving aspect ratio'
    'remove-bg:Remove backgrounds using local AI'
    'edit:Open in editor, watch for saves, sync back'
    'pull:Download attachments to a local directory'
    'push:Upload a local file to the media library'
    'references:Show where an attachment is used'
    'update:Check for updates and self-update'
    'completions:Generate shell completion scripts'
    'help:Display help for a command'
  )

  global_opts=(
    '--site[Override the active site]:site name:'
    '--json[Machine-readable JSON output]'
    '--quiet[Errors only]'
    '--concurrency[Parallel workers for bulk ops]:number:'
    '--dry-run[Show what would happen without executing]'
    '--apply[Opt out of dry-run for bulk ops]'
    '--yes[Skip confirmation prompts]'
    '--strict[Fail loudly when capability fallbacks would activate]'
    '(-h --help)'{-h,--help}'[Display help]'
    '(-v --version)'{-v,--version}'[Output version]'
  )

  if (( CURRENT == 2 )); then
    _describe -t commands 'localpress command' commands
    _arguments -s $global_opts
    return
  fi

  case $words[2] in
    init)
      _arguments -s \\
        '--site[Override site]:site name:' \\
        '(-h --help)'{-h,--help}'[Display help]'
      ;;
    doctor)
      _arguments -s \\
        '--all-sites[Show capabilities for every configured site]' \\
        '--plugins[Probe for relevant WordPress plugins]' \\
        '--fix[Attempt to auto-remediate detected issues]' \\
        '(-h --help)'{-h,--help}'[Display help]'
      ;;
    list)
      _arguments -s \\
        '(-i --interactive)'{-i,--interactive}'[Interactive TUI browser]' \\
        '--unoptimized[Only show unoptimized items]' \\
        '--type[Filter by MIME type]:type:(image/jpeg image/png image/webp image/avif)' \\
        '--sort[Sort field]:field:(date name size id)' \\
        '--order[Sort order]:order:(asc desc)' \\
        '--limit[Items per page]:number:' \\
        '--page[Page number]:number:' \\
        '(-h --help)'{-h,--help}'[Display help]'
      ;;
    stats)
      _arguments -s \\
        '--all-sites[Show stats for every configured site]' \\
        '(-h --help)'{-h,--help}'[Display help]'
      ;;
    optimize)
      _arguments -s \\
        '--all[Process all attachments]' \\
        '--unoptimized[Process only unoptimized items]' \\
        '--quality[Target quality (1-100)]:quality:' \\
        '--format[Output format]:format:(webp avif jpeg png)' \\
        '--max-width[Maximum width]:pixels:' \\
        '--max-height[Maximum height]:pixels:' \\
        '--encoder[Encoding backend]:encoder:(sharp jsquash)' \\
        '--strip-metadata[Remove EXIF data]' \\
        '--profile[Use named profile]:profile:' \\
        '--keep-original[Upload as new attachment]' \\
        '--preview[Open browser preview UI]' \\
        '(-h --help)'{-h,--help}'[Display help]' \\
        '*:attachment ID:'
      ;;
    convert)
      _arguments -s \\
        '--format[Target format]:format:(webp avif jpeg png)' \\
        '--quality[Target quality (1-100)]:quality:' \\
        '--encoder[Encoding backend]:encoder:(sharp jsquash)' \\
        '--keep-original[Upload as new attachment]' \\
        '(-h --help)'{-h,--help}'[Display help]' \\
        '*:attachment ID:'
      ;;
    resize)
      _arguments -s \\
        '--max-width[Maximum width]:pixels:' \\
        '--max-height[Maximum height]:pixels:' \\
        '--keep-original[Upload as new attachment]' \\
        '(-h --help)'{-h,--help}'[Display help]' \\
        '*:attachment ID:'
      ;;
    remove-bg)
      _arguments -s \\
        '--all[Process all attachments]' \\
        '--unoptimized[Process only unprocessed items]' \\
        '--model[ONNX model]:model:(u2net u2netp silueta isnet-general-use birefnet-lite)' \\
        '--bg[Background color]:color:' \\
        '--trim[Remove transparent borders]' \\
        '--list-models[Show available models]' \\
        '--keep-original[Upload as new attachment]' \\
        '--rembg[Use system Python rembg]' \\
        '--rembg-model[Rembg model name]:model:' \\
        '--preview[Open browser preview UI]' \\
        '(-h --help)'{-h,--help}'[Display help]' \\
        '*:attachment ID:'
      ;;
    caption)
      _arguments -s \\
        '--missing-alt[Only caption images without alt text]' \\
        '--model[Ollama model]:model:' \\
        '--prompt[Custom prompt]:prompt:' \\
        '--list-models[Show available Ollama models]' \\
        '(-h --help)'{-h,--help}'[Display help]' \\
        '*:attachment ID:'
      ;;
    audit)
      _arguments -s \\
        '--unoptimized[Find unoptimized images]' \\
        '--large[Find images over threshold]' \\
        '--missing-alt[Find images without alt text]' \\
        '--display-size[Find oversized images]' \\
        '--duplicates[Find perceptual duplicates]' \\
        '--broken-refs[Find broken attachment URLs]' \\
        '--orphans[Find orphan files on disk]' \\
        '--all[Run all audit checks]' \\
        '--threshold[Size threshold in bytes]:bytes:' \\
        '(-h --help)'{-h,--help}'[Display help]'
      ;;
    edit)
      _arguments -s \\
        '--with[Editor application]:editor:' \\
        '--no-watch[Open without watching for saves]' \\
        '--keep-file[Preserve temp file after editing]' \\
        '--to[Download to specific directory]:directory:_directories' \\
        '(-h --help)'{-h,--help}'[Display help]' \\
        ':attachment ID:'
      ;;
    pull)
      _arguments -s \\
        '--to[Download directory]:directory:_directories' \\
        '(-h --help)'{-h,--help}'[Display help]' \\
        '*:attachment ID:'
      ;;
    push)
      _arguments -s \\
        '--title[Attachment title]:title:' \\
        '--alt[Alt text]:alt:' \\
        '--caption[Caption]:caption:' \\
        '--description[Description]:description:' \\
        '--post-id[Attach to post]:post ID:' \\
        '(-h --help)'{-h,--help}'[Display help]' \\
        ':file:_files'
      ;;
    references)
      _arguments -s \\
        '--scope[Scan scope]:scope:(fast full)' \\
        '--update-to[Rewrite references to new ID]:new ID:' \\
        '(-h --help)'{-h,--help}'[Display help]' \\
        ':attachment ID:'
      ;;
    update)
      _arguments -s \\
        '--check[Just check without installing]' \\
        '(-h --help)'{-h,--help}'[Display help]'
      ;;
    completions)
      _arguments -s \\
        ':shell:(bash zsh fish)' \\
        '(-h --help)'{-h,--help}'[Display help]'
      ;;
    *)
      _arguments -s $global_opts
      ;;
  esac
}

_localpress "$@"
`;
}

// -- Fish completions ---------------------------------------------------------

function generateFish(): string {
  const lines: string[] = [
    '# localpress fish completion',
    '# Generated by: localpress completions fish',
    '# Save to: ~/.config/fish/completions/localpress.fish',
    '#   localpress completions fish > ~/.config/fish/completions/localpress.fish',
    '',
    '# Disable file completions by default',
    'complete -c localpress -f',
    '',
    '# Global options',
    'complete -c localpress -l site -d "Override the active site" -r',
    'complete -c localpress -l json -d "Machine-readable JSON output"',
    'complete -c localpress -l quiet -d "Errors only"',
    'complete -c localpress -l concurrency -d "Parallel workers for bulk ops" -r',
    'complete -c localpress -l dry-run -d "Show what would happen"',
    'complete -c localpress -l apply -d "Opt out of dry-run for bulk ops"',
    'complete -c localpress -l yes -d "Skip confirmation prompts"',
    'complete -c localpress -l strict -d "Fail loudly on capability fallbacks"',
    'complete -c localpress -s h -l help -d "Display help"',
    'complete -c localpress -s v -l version -d "Output version"',
    '',
    '# Commands',
    ...fishCommand('init', 'Connect a WordPress site'),
    ...fishCommand('sites', 'Manage configured WordPress sites'),
    ...fishCommand('doctor', 'Show backend availability and capability matrix'),
    ...fishCommand('config', 'Read and write localpress configuration'),
    ...fishCommand('list', 'List media in the active site library'),
    ...fishCommand('show', 'Show metadata and history for an attachment'),
    ...fishCommand('stats', 'Show cumulative processing stats'),
    ...fishCommand('caption', 'Generate alt-text using a local vision model'),
    ...fishCommand('audit', 'Find optimization opportunities'),
    ...fishCommand('optimize', 'Compress and optionally convert media'),
    ...fishCommand('convert', 'Convert attachments to a different format'),
    ...fishCommand('resize', 'Resize attachments preserving aspect ratio'),
    ...fishCommand('remove-bg', 'Remove backgrounds using local AI'),
    ...fishCommand('edit', 'Open in editor, watch for saves, sync back'),
    ...fishCommand('pull', 'Download attachments to a local directory'),
    ...fishCommand('push', 'Upload a local file to the media library'),
    ...fishCommand('references', 'Show where an attachment is used'),
    ...fishCommand('update', 'Check for updates and self-update'),
    ...fishCommand('completions', 'Generate shell completion scripts'),
    ...fishCommand('help', 'Display help for a command'),
    '',
    '# Subcommand options',
    ...fishSubOpt('doctor', '--all-sites', 'Show capabilities for every site'),
    ...fishSubOpt('doctor', '--plugins', 'Probe for relevant WordPress plugins'),
    ...fishSubOpt('doctor', '--fix', 'Attempt to auto-remediate issues'),
    '',
    ...fishSubOpt('list', '-i', 'Interactive TUI browser', '-s i'),
    ...fishSubOpt('list', '--interactive', 'Interactive TUI browser'),
    ...fishSubOpt('list', '--unoptimized', 'Only show unoptimized items'),
    ...fishSubOpt('list', '--type', 'Filter by MIME type', '-r'),
    ...fishSubOpt('list', '--sort', 'Sort field', '-r -a "date name size id"'),
    ...fishSubOpt('list', '--order', 'Sort order', '-r -a "asc desc"'),
    ...fishSubOpt('list', '--limit', 'Items per page', '-r'),
    ...fishSubOpt('list', '--page', 'Page number', '-r'),
    '',
    ...fishSubOpt('stats', '--all-sites', 'Show stats for every site'),
    '',
    ...fishSubOpt('optimize', '--all', 'Process all attachments'),
    ...fishSubOpt('optimize', '--unoptimized', 'Process only unoptimized items'),
    ...fishSubOpt('optimize', '--quality', 'Target quality (1-100)', '-r'),
    ...fishSubOpt('optimize', '--format', 'Output format', '-r -a "webp avif jpeg png"'),
    ...fishSubOpt('optimize', '--max-width', 'Maximum width', '-r'),
    ...fishSubOpt('optimize', '--max-height', 'Maximum height', '-r'),
    ...fishSubOpt('optimize', '--encoder', 'Encoding backend', '-r -a "sharp jsquash"'),
    ...fishSubOpt('optimize', '--strip-metadata', 'Remove EXIF data'),
    ...fishSubOpt('optimize', '--profile', 'Use named profile', '-r'),
    ...fishSubOpt('optimize', '--keep-original', 'Upload as new attachment'),
    ...fishSubOpt('optimize', '--preview', 'Open browser preview UI'),
    '',
    ...fishSubOpt('convert', '--format', 'Target format', '-r -a "webp avif jpeg png"'),
    ...fishSubOpt('convert', '--quality', 'Target quality (1-100)', '-r'),
    ...fishSubOpt('convert', '--encoder', 'Encoding backend', '-r -a "sharp jsquash"'),
    ...fishSubOpt('convert', '--keep-original', 'Upload as new attachment'),
    '',
    ...fishSubOpt('resize', '--max-width', 'Maximum width', '-r'),
    ...fishSubOpt('resize', '--max-height', 'Maximum height', '-r'),
    ...fishSubOpt('resize', '--keep-original', 'Upload as new attachment'),
    '',
    ...fishSubOpt('remove-bg', '--all', 'Process all attachments'),
    ...fishSubOpt(
      'remove-bg',
      '--model',
      'ONNX model',
      '-r -a "u2net u2netp silueta isnet-general-use birefnet-lite"',
    ),
    ...fishSubOpt('remove-bg', '--bg', 'Background color', '-r'),
    ...fishSubOpt('remove-bg', '--trim', 'Remove transparent borders'),
    ...fishSubOpt('remove-bg', '--list-models', 'Show available models'),
    ...fishSubOpt('remove-bg', '--keep-original', 'Upload as new attachment'),
    ...fishSubOpt('remove-bg', '--rembg', 'Use system Python rembg'),
    ...fishSubOpt('remove-bg', '--rembg-model', 'Rembg model name', '-r'),
    ...fishSubOpt('remove-bg', '--preview', 'Open browser preview UI'),
    '',
    ...fishSubOpt('caption', '--missing-alt', 'Only caption images without alt text'),
    ...fishSubOpt('caption', '--model', 'Ollama model', '-r'),
    ...fishSubOpt('caption', '--prompt', 'Custom prompt', '-r'),
    ...fishSubOpt('caption', '--list-models', 'Show available Ollama models'),
    '',
    ...fishSubOpt('audit', '--unoptimized', 'Find unoptimized images'),
    ...fishSubOpt('audit', '--large', 'Find images over threshold'),
    ...fishSubOpt('audit', '--missing-alt', 'Find images without alt text'),
    ...fishSubOpt('audit', '--display-size', 'Find oversized images'),
    ...fishSubOpt('audit', '--duplicates', 'Find perceptual duplicates'),
    ...fishSubOpt('audit', '--broken-refs', 'Find broken attachment URLs'),
    ...fishSubOpt('audit', '--orphans', 'Find orphan files on disk'),
    ...fishSubOpt('audit', '--all', 'Run all audit checks'),
    ...fishSubOpt('audit', '--threshold', 'Size threshold in bytes', '-r'),
    '',
    ...fishSubOpt('edit', '--with', 'Editor application', '-r'),
    ...fishSubOpt('edit', '--no-watch', 'Open without watching'),
    ...fishSubOpt('edit', '--keep-file', 'Preserve temp file'),
    ...fishSubOpt('edit', '--to', 'Download directory', '-r -F'),
    '',
    ...fishSubOpt('pull', '--to', 'Download directory', '-r -F'),
    '',
    ...fishSubOpt('push', '--title', 'Attachment title', '-r'),
    ...fishSubOpt('push', '--alt', 'Alt text', '-r'),
    ...fishSubOpt('push', '--caption', 'Caption', '-r'),
    ...fishSubOpt('push', '--description', 'Description', '-r'),
    ...fishSubOpt('push', '--post-id', 'Attach to post', '-r'),
    '',
    ...fishSubOpt('references', '--scope', 'Scan scope', '-r -a "fast full"'),
    ...fishSubOpt('references', '--update-to', 'Rewrite references to new ID', '-r'),
    '',
    ...fishSubOpt('update', '--check', 'Just check without installing'),
    '',
    '# completions subcommand',
    'complete -c localpress -n "__fish_seen_subcommand_from completions" -a "bash zsh fish" -d "Shell type"',
    '',
  ];

  return lines.join('\n');
}

function fishCommand(name: string, desc: string): string[] {
  return [`complete -c localpress -n "__fish_use_subcommand" -a "${name}" -d "${desc}"`];
}

function fishSubOpt(cmd: string, opt: string, desc: string, extra = ''): string[] {
  const flag = opt.startsWith('--') ? `-l ${opt.slice(2)}` : `-s ${opt.slice(1)}`;
  const extraStr = extra ? ` ${extra}` : '';
  return [
    `complete -c localpress -n "__fish_seen_subcommand_from ${cmd}" ${flag} -d "${desc}"${extraStr}`,
  ];
}
