/**
 * `localpress title [ids...]` — AI-generated short title for attachment(s).
 *
 * Companion to `caption` (which generates alt text). Writes to the WP
 * `post_title` field via the adapter's updateMetadata. Same plumbing as
 * caption: Ollama vision model, pre-flight check, idempotent-skip,
 * time-machine snapshot, safe-by-default bulk ops.
 *
 * Typical use: clean up titles for attachments whose filenames are
 * machine-generated ("Screenshot-2026-05-06-at-5.20.18-PM" →
 * "Terminal command output").
 */

import type { Command } from 'commander';
import { AdapterResolver } from '../../adapters/resolver.ts';
import type { WpBackend } from '../../adapters/types.ts';
import { DEFAULT_OLLAMA_MODEL, DEFAULT_OLLAMA_URL } from '../../engine/caption/ollama.ts';
import { preflightOllama, runBulkVision } from '../../engine/caption/run-bulk.ts';
import { resolveHistoryConfig } from '../../engine/history/index.ts';
import { SiteDb } from '../../engine/state/db.ts';
import { getConfigDir, getSiteDbPath, loadConfig, resolveActiveSite } from '../utils/config.ts';
import { parseAttachmentIds } from '../utils/ids.ts';
import { error, info, printJson, warn } from '../utils/output.ts';
import { resolveDryRun } from '../utils/run-mode.ts';

export function registerTitleCommand(program: Command): void {
  program
    .command('title [ids...]')
    .description(
      "AI-generated short title (3-7 word noun phrase) written to the attachment's WP title.",
    )
    .option(
      '--model <name>',
      `Ollama vision model. Resolution: --model > config.defaults.captionModel > ${DEFAULT_OLLAMA_MODEL}`,
    )
    .option(
      '--ollama-url <url>',
      `Ollama base URL (default: ${DEFAULT_OLLAMA_URL})`,
      DEFAULT_OLLAMA_URL,
    )
    .option('--all', 'process all image attachments (dry-run unless --apply)')
    .option(
      '--missing-title',
      'only items whose title still looks auto-generated (Screenshot-…, IMG_…)',
    )
    .option('--language <lang>', 'generate in this language (e.g. "Spanish")')
    .option('--overwrite', 'replace existing titles (default: skip if already set non-trivially)')
    .action(async (idStrs: string[], options) => {
      const parentOpts = program.opts();

      const config = await loadConfig();
      const site = resolveActiveSite(config, parentOpts.site);
      const resolver = new AdapterResolver(site);
      const listAdapter = resolver.resolve('list');
      const getAdapter = resolver.resolve('get');
      const metaAdapter = resolver.resolve('update-meta');

      const effectiveModel: string =
        options.model ?? config.defaults?.captionModel ?? DEFAULT_OLLAMA_MODEL;

      const preflightError = await preflightOllama(effectiveModel, options.ollamaUrl);
      if (preflightError) {
        error(preflightError);
        process.exit(2);
      }

      const isBulk = !idStrs.length && (options.missingTitle || options.all);
      const isDryRun = resolveDryRun(parentOpts, isBulk);

      if (!idStrs.length && !isBulk) {
        error(
          'Specify attachment IDs, --missing-title, or --all.\n' +
            '  localpress title 123 124\n' +
            '  localpress title --missing-title --apply',
        );
        process.exit(2);
      }

      // Resolve target IDs.
      let ids: number[];
      if (idStrs.length > 0) {
        ids = parseAttachmentIds(idStrs);
      } else {
        info('  Fetching image attachments…');
        const all = await fetchAllImages(listAdapter);
        if (options.missingTitle) {
          ids = all.filter((m) => looksAutoGenerated(m.title)).map((m) => m.id);
        } else {
          ids = all.map((m) => m.id);
        }
        info(`  Found ${ids.length} target attachment(s).`);
      }

      if (ids.length === 0) {
        info('  Nothing to do.');
        return;
      }

      if (isBulk && isDryRun) {
        info('  Dry-run: pass --apply to write titles to WordPress.\n');
      }

      const db = SiteDb.init(getSiteDbPath(site.name));
      db.ensureSite(site.name, site.url);

      const historyConfig = resolveHistoryConfig(config.history);

      const result = await runBulkVision({
        ids,
        isDryRun,
        effectiveModel,
        ollamaUrl: options.ollamaUrl,
        language: options.language,
        getAdapter,
        metaAdapter,
        db,
        siteName: site.name,
        siteUrl: site.url,
        configDir: getConfigDir(),
        historyEnabled: historyConfig.enabled,
        historyMaxSizeBytes: historyConfig.maxSizeBytes ?? 0,
        options: {
          kind: 'title',
          operation: 'title',
          buildUpdate: (generated) => ({ title: generated }),
          // For "missing title" detection we treat auto-generated titles as
          // "no title set" — so even if WP has "Screenshot-…" as the title,
          // we generate a new one when --overwrite is not set.
          readPrevious: (item) => (looksAutoGenerated(item.title) ? undefined : item.title),
          overwrite: options.overwrite ?? false,
          preflightSkip: (item) =>
            item.mimeType.startsWith('image/') ? undefined : 'not an image',
        },
        onItemStart: (item) => info(`  Titling #${item.id} (${item.filename})…`),
        onItemSuccess: (_item, generated, durationMs) =>
          info(`    ✓ "${generated}" (${durationMs}ms)`),
        onItemSkip: (item, reason) => info(`  — #${item.id} (${item.filename}) — ${reason}`),
        onItemError: (id, message) => error(`    ✗ #${id}: ${message}`),
      });

      db.close();

      if (parentOpts.json) {
        printJson({
          dryRun: isDryRun,
          ...result,
        });
        return;
      }

      const dryNote = isDryRun ? ' (dry run — WordPress not updated)' : '';
      if (result.processed + result.skipped > 0 || result.failures > 0) {
        info(
          `\n  Done: ${result.processed} titled, ${result.skipped} skipped, ${result.failures} failed${dryNote}.`,
        );
      }

      if (result.failures > 0) process.exit(1);
    });
}

/** WP titles that look machine-generated and should be regenerated. */
function looksAutoGenerated(title: string | undefined): boolean {
  if (!title) return true;
  const t = title.trim();
  if (t.length === 0) return true;
  return (
    /^screenshot[\s_-]/i.test(t) ||
    /^image[\s_-]?\d+/i.test(t) ||
    /^img[\s_-]?\d+/i.test(t) ||
    /^dsc[\s_-]?\d+/i.test(t) ||
    /^untitled/i.test(t) ||
    /^\d+$/.test(t) ||
    /^[a-f0-9]{8,}$/i.test(t) // hex hash filenames
  );
}

async function fetchAllImages(adapter: WpBackend): Promise<Array<{ id: number; title: string }>> {
  const out: Array<{ id: number; title: string }> = [];
  let page = 1;
  while (true) {
    try {
      const result = await adapter.listMediaPage({ type: 'image/', perPage: 100, page });
      out.push(...result.items.map((i) => ({ id: i.id, title: i.title })));
      if (page >= result.totalPages) break;
      page++;
    } catch (err) {
      warn(`  Pagination stopped: ${err instanceof Error ? err.message : String(err)}`);
      break;
    }
  }
  return out;
}
